name: Format

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check
